# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Sherry Shao"
description: "World friends are real friends too"

email: sshao0123@gmail.com
#blog logo
logo: "/assets/images/avatar.jpg"
float_logo: false # true, false (default)

# blog cover
cover: "/assets/images/background_image.jpg"

name: 'Sherry Shao'
author: 'Sherry Shao'
author_image: "/assets/images/avatar.jpg"

paginate:	5

url: "" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@sherryshao_'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/sherryshao_

  - icon:	linkedin
    url:	https://www.linkedin.com/in/sherryshao

  - icon:	github
    url:	https://github.com/sherryshao

  - icon: instagram
    url:  https://www.instagram.com/sherryshao_
